services:
  backend:
    build: .
    container_name: netamap-backend
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    command: node src/api/server.js

  frontend:
    build: ./frontend
    container_name: netamap-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
